package emulator.dto.enums

enum class DriverStatusType {
    DRIVER_STATUS_INITIALIZATION,
    DRIVER_STATUS_ERROR,
    DRIVER_STATUS_CONNECTION_ERROR,
    DRIVER_STATUS_DISABLED,
    DRIVER_STATUS_SLEEP,
    DRIVER_STATUS_SETTING_POSITION
}