mqtt:
  broker-addr: 192.168.1.7
  broker-port: 1883
  qos-level: 1

logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/handcontrol_db
    username: handcontrol_user
    password: elephant
  jpa:
    generate-ddl: true
