mqtt:
  broker-addr: 192.168.1.7
  broker-port: 1883
  qos-level: 1

logging:
  level:
    root: info

spring:
#  todo change to server configuration
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: password
  jpa:
    generate-ddl: true
